export default {
  // important
  FACEBOOK_APP_ID : "377170089537556",
  ANDROID_CLIENT_ID : "925139916251-o8646r93rhvt53j7sf5ggmf28khgqvrn.apps.googleusercontent.com",
  
  ITEMS_PER_PAGE : 30,
  // SERVER_URL :"http://localhost:3000",
  // UPLOAD_SERVER_URL : "http://localhost:3001",
  SERVER_URL : "http://chemi.rsad.kr",
  UPLOAD_SERVER_URL : "http://upload.rsad.kr",
  CategoryName : {
    all : "",
    skin_care : "Skin care",
    mask : "Mask",
    sun_care : "Sun care",
    make_up : "Make up",
    cleansing : "Cleansing",
    body : "Body",
    hair : "Hair",
    nail : "Nail",
    perfume : "Perfume",
    oral : "Oral",
    baby : "Baby",
    men : "Men",
  },
  SubCategoryname : {
    toner: "Toner",
    lotion: "Lotion",
    cream: "Cream",
    sun_block: "Sun block",
    after_care: "After care",
    base: "Base",
    eye : "Eye",
    lip: "Lip",
    remover: "Remover",
    cleanser: "Cleanser",
    peeling: "Peeling",
    cleanser: "Cleanser",
    lotion: "Lotion",
    shampoo: "Shampoo",
    treatment: "Treatment",
    essense: "Essense",
    colors: "Colors",
    nail_care: "Nail care",
    toothpaste: "Toothpaste",
  },  
  Loading_text:"Loading...",
  ASYNC_PARAMS : {
    login_info : "LoginInfo"
  },
  NAVIGATION_PARAMS : {
    item_id: "item_id",
    back_page: "back_page",
    product_container_initial_page: "product_container_initial_page",
  },
};
