export default {
  // important
  FACEBOOK_APP_ID : "377170089537556",
  ANDROID_CLIENT_ID : "921753193053-0paacaalh9idjhu84p0ssmjmdkqs11m3.apps.googleusercontent.com",
  IOS_CLIENT_ID : "921753193053-edfubitfhjom9qjul66c1k50pceukqr8.apps.googleusercontent.com",
  
  ITEMS_PER_PAGE : 30,
  SERVER_URL :"http://192.168.0.74:3000",
  UPLOAD_SERVER_URL : "http://192.168.0.74:3001",
  // SERVER_URL : "http://chemi.rsad.kr",
  // UPLOAD_SERVER_URL : "http://upload.rsad.kr",
  SkinTypeName : {
    dry: "Dry",
    oily: "Oily",
    complex: "Complex",
  },
  ConcernName : {
    acne: "Acne",
    wrinkle: "Wrinkle",
    pores: "Pores",
    complex: "Complex",
    redness: "Redness",
    rashes: "Rashes",
  },
  NeedsName : {
    whitening: "Whitening",
    anti_Aging: "Anti-Aging",
    moisturizing: "Moisturizing",
  },
  CategoryName : {
    all : "",
    skin_care : "Skin care",
    mask : "Mask",
    sun_care : "Sun care",
    make_up : "Make up",
    cleansing : "Cleansing",
    body : "Body",
    hair : "Hair",
    nail : "Nail",
    perfume : "Perfume",
    oral : "Oral",
    baby : "Baby",
    men : "Men",
  },
  SubCategoryname : {
    toner: "Toner",
    lotion: "Lotion",
    cream: "Cream",
    sun_block: "Sun block",
    after_care: "After care",
    base: "Base",
    eye : "Eye",
    lip: "Lip",
    remover: "Remover",
    cleanser: "Cleanser",
    peeling: "Peeling",
    cleanser: "Cleanser",
    lotion: "Lotion",
    shampoo: "Shampoo",
    treatment: "Treatment",
    essense: "Essense",
    colors: "Colors",
    nail_care: "Nail care",
    toothpaste: "Toothpaste",
  },  
  Loading_text:"Loading...",
  ASYNC_PARAMS : {
    login_info : "LoginInfo",
    noti_setting : "noti_setting",
    setting : "setting",
    recent_search_words: "recent_search_words",
    like_list_order: "like_list_order",
    user_pwd: "user_pwd",
  },
  NAVIGATION_PARAMS : {
    item_id: "item_id",
    back_page: "back_page",
    product_container_initial_page: "product_container_initial_page",
    search_word: "search_word",
    onDaySelect: "onDaySelect",
    onProfileEdited: "profileEdited",
  },
};
